### ISSUE TITLE
Lutron Caseta - add 4th speed button

### ISSUE THREAD

**Issue by magnetic157** [finity69x2/fan-percent-button-row#15] opened 2021-06-22 17:17 UTC
Hello, can we have a 4th button option?

Lutron Caseta offers 25%, 50%, 75% and 100% fan speeds - the current setup only seems to allow 3 speeds on the percentage section.  Maybe make the 4th speed button visibility optional for those who only need 3.

**Comment by kquinsland** [comment] 2021-06-27 17:04
Duplicate of #14

**Comment by finity69x2** [comment] 2021-07-29 22:55
duplicate

**Closed as completed by finity69x2** 2021-07-29 22:55 UTC
